### ISSUE TITLE
[Feature] Netbox REST API integration

### ISSUE THREAD

**Issue by zombah** [cpmarvin/lnetd_qt#1]
Hello,
It will be very convenient if this tool able to read topology from Netbox REST API interface with ability to filter, like load devices with for example tag 'simulate' or 'visualize'.

Thanks for this project, it looks very promising!

**Comment by cpmarvin** [comment]
hi @zombah 

i was planning to link the lnetd -web api with this tool. So that an user can set the link to LnetD web application api to get the topology. 

http://demo.lnetd.co.uk/api/get_isis_links 

In a similar fashion i can expose the http://demo.lnetd.co.uk/data/topology_netbox via api and load that in. As the IP's are not in the netbox topology that will be random generated , same goes for IGP metric.

**Comment by zombah** [comment]
After watching your videos i imagined some kind of standalone mode with loadind data from netbox, something like as visualisation studio for netbox data.

**Comment by cpmarvin** [comment]
Yes , that is the plan. A self contain app that can load any topology or build your own. 

I can add a python script to get data from netbox ( for example all router to router links and all circuits ) and save that to a json file , so that it can be loaded into lnetd_qt. 

It will be a two step process , get data from netbox -> save as json -> load json into lnetd_qt.

**Comment by cpmarvin** [comment]
@zombah 

Let me know if this works for you. https://github.com/cpmarvin/lnetd_qt/commit/97ea87db9aae46977b8fbecd43dc4a6478dbdc98 

thx.

**Comment by zombah** [comment]
@cpmarvin Works perfect, thank you!
